language: node_js
node_js:
- "16"
jobs:
  include:
    - stage: success build
      install:
        - npm install
      script:
        - npm run success-test
      after_script:
        - echo job finished
    - stage: failure build
      install:
        - npm install
      script:
        - npm run failure-test
      after_script:
        - echo job finished
    - stage: all build
      install:
        - npm install
      script:
        - npm run test
      after_script:
        - echo job finished
